/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ranges/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Range */
        post: operations["parse_range_ranges_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equity/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Equity */
        post: operations["calculate_equity_equity_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solver/push-fold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve Push Fold Route */
        post: operations["solve_push_fold_route_solver_push_fold_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solver/preflop-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve Preflop Tree Route */
        post: operations["solve_preflop_tree_route_solver_preflop_tree_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainer/push-fold/spot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spot */
        get: operations["get_spot_trainer_push_fold_spot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainer/push-fold/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade Spot */
        post: operations["grade_spot_trainer_push_fold_grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainer/preflop-tree/spot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tree Spot */
        get: operations["get_tree_spot_trainer_preflop_tree_spot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainer/preflop-tree/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade Tree Spot */
        post: operations["grade_tree_spot_trainer_preflop_tree_grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EquityRequest */
        EquityRequest: {
            /** Hero */
            hero: string;
            /** Villain */
            villain: string;
            /**
             * Board
             * @default
             */
            board: string;
            /**
             * Iterations
             * @default 5000
             */
            iterations: number;
        };
        /** EquityResponse */
        EquityResponse: {
            /** Win */
            win: number;
            /** Tie */
            tie: number;
            /** Lose */
            lose: number;
            /** Equity */
            equity: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PreflopTreeRequest */
        PreflopTreeRequest: {
            /** Stack Bb */
            stack_bb: number;
        };
        /** PreflopTreeResponse */
        PreflopTreeResponse: {
            /** Stack Bb */
            stack_bb: number;
            /** Open Size Bb */
            open_size_bb: number;
            /** Threebet Size Bb */
            threebet_size_bb: number;
            /** Iterations */
            iterations: number;
            /** Sb Root */
            sb_root: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Bb Vs Open */
            bb_vs_open: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Sb Vs 3Bet */
            sb_vs_3bet: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Bb Vs Shove */
            bb_vs_shove: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Sb Vs Shove After Open */
            sb_vs_shove_after_open: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Bb Vs Shove After 3Bet */
            bb_vs_shove_after_3bet: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Caveat */
            caveat: string;
        };
        /** PushFoldGradeRequest */
        PushFoldGradeRequest: {
            /** Stack Bb */
            stack_bb: number;
            /** Hero Class */
            hero_class: string;
            /**
             * Action
             * @enum {string}
             */
            action: "shove" | "fold";
        };
        /** PushFoldGradeResponse */
        PushFoldGradeResponse: {
            /** Correct */
            correct: boolean;
            /**
             * Correct Action
             * @enum {string}
             */
            correct_action: "shove" | "fold";
            /** Shove Frequency */
            shove_frequency: number;
        };
        /** PushFoldRequest */
        PushFoldRequest: {
            /** Stack Bb */
            stack_bb: number;
        };
        /** PushFoldResponse */
        PushFoldResponse: {
            /** Stack Bb */
            stack_bb: number;
            /** Iterations */
            iterations: number;
            /** Sb Shove Frequency */
            sb_shove_frequency: {
                [key: string]: number;
            };
            /** Bb Call Frequency */
            bb_call_frequency: {
                [key: string]: number;
            };
        };
        /** PushFoldSpotResponse */
        PushFoldSpotResponse: {
            /** Stack Bb */
            stack_bb: number;
            /** Hero Class */
            hero_class: string;
            /** Hero Combo */
            hero_combo: string;
        };
        /** RangeParseRequest */
        RangeParseRequest: {
            /** Notation */
            notation: string;
        };
        /** RangeParseResponse */
        RangeParseResponse: {
            /** Classes */
            classes: {
                [key: string]: number;
            };
            /** Combo Count */
            combo_count: number;
        };
        /** TreeGradeRequest */
        TreeGradeRequest: {
            /** Stack Bb */
            stack_bb: number;
            /** Hero Class */
            hero_class: string;
            /**
             * Action
             * @enum {string}
             */
            action: "fold" | "open" | "shove";
        };
        /** TreeGradeResponse */
        TreeGradeResponse: {
            /** Correct */
            correct: boolean;
            /**
             * Correct Action
             * @enum {string}
             */
            correct_action: "fold" | "open" | "shove";
            /** Action Frequencies */
            action_frequencies: {
                [key: string]: number;
            };
            /** Caveat */
            caveat: string;
        };
        /** TreeSpotResponse */
        TreeSpotResponse: {
            /** Stack Bb */
            stack_bb: number;
            /** Hero Class */
            hero_class: string;
            /** Hero Combo */
            hero_combo: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    parse_range_ranges_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RangeParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_equity_equity_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_push_fold_route_solver_push_fold_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushFoldRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushFoldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_preflop_tree_route_solver_preflop_tree_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreflopTreeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreflopTreeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spot_trainer_push_fold_spot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushFoldSpotResponse"];
                };
            };
        };
    };
    grade_spot_trainer_push_fold_grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushFoldGradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushFoldGradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_spot_trainer_preflop_tree_spot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeSpotResponse"];
                };
            };
        };
    };
    grade_tree_spot_trainer_preflop_tree_grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TreeGradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeGradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
