"""add ranges table

Revision ID: 9652888dc06a
Revises: 8c663adeae1f
Create Date: 2026-07-24 00:03:05.340743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9652888dc06a'
down_revision: Union[str, Sequence[str], None] = '8c663adeae1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('classes_json', sa.String(), nullable=False),
    sa.Column('notation', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('factors_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranges_name'), 'ranges', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranges_name'), table_name='ranges')
    op.drop_table('ranges')
    # ### end Alembic commands ###
